<% const elasticsearchReplicas = process.env.CI_COMMIT_REF_NAME === "master" ? 1 : 1 %>

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: <%- namespace %>
spec:
  replicas: <%- elasticsearchReplicas %>
  serviceName: elasticsearch
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 90
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: elasticsearch
                topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 150
      initContainers:
        - name: fix-the-volume-permission
          image: busybox
          command:
            - sh
            - -c
            - chown -R 1000:1000 /usr/share/elasticsearch/data
          securityContext:
            privileged: true
          volumeMounts:
            - name: data
              mountPath: /usr/share/elasticsearch/data
        - name: increase-the-vm-max-map-count
          image: busybox
          command:
            - sysctl
            - -w
            - vm.max_map_count=262144
          securityContext:
            privileged: true
        - name: increase-the-ulimit
          image: busybox
          command:
            - sh
            - -c
            - ulimit -n 65536
          securityContext:
            privileged: true
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.6.1
          ports:
            - containerPort: 9200
              name: http
            - containerPort: 9300
              name: tcp
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: node.name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: cluster.name
              value: <%- namespace %>-elasticsearch-cluster
            - name: cluster.initial_master_nodes
              value: <%- new Array(elasticsearchReplicas).fill(0).map((_, i) => "elasticsearch-" + i).join(",") %>
            - name: transport.host
              value: 127.0.0.1
            - name: http.host
              value: 0.0.0.0
            - name: ES_JAVA_OPTS
              value: -Xms300m -Xmx300m
          volumeMounts:
            - name: data
              mountPath: /usr/share/elasticsearch/data
          readinessProbe:
            httpGet:
              path: /_cluster/health
              port: http
            initialDelaySeconds: 20
            timeoutSeconds: 5
          resources:
            limits:
              memory: 2Gi
              cpu: 500m
            requests:
              memory: 500Mi
              cpu: 10m
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: ssd
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
---

<% for (let i = 0; i < elasticsearchReplicas; ++i) { %>
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-<%-i%>
  namespace: <%- namespace %>
spec:
  ports:
    - port: 9200
      name: http
    - port: 9300
      name: tcp
  selector:
    statefulset.kubernetes.io/pod-name: elasticsearch-<%-i%>
---
<% } %>

apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: <%- namespace %>
spec:
  ports:
    - port: 9200
      name: http
    - port: 9300
      name: tcp
  selector:
    app: elasticsearch
---
